### ISSUE TITLE
24h clock shows the 24th hour, e.g. 24:03 or 24:59

### ISSUE THREAD

**Issue by lollilol** [joelshepherd/tabliss#362]
![image](https://user-images.githubusercontent.com/38194372/112905818-5ef8a580-90eb-11eb-8f89-11ab6aafb8bf.png)
normally the clock should end with 23:59 and then it should switch to 00:00, 00:01 and so on (the next day starts)
If it shows 24:59 its basically saying that the day has 25 hours lmao

**Comment by trickypr** [comment]
Odd. This should have been fixed with 2.1.0. What version are you running?

**Comment by lollilol** [comment]
Im running 2.1.0 both in firefox and chrome and while it works in firefox, it doesnt work in chrome..
this is chrome
![image](https://user-images.githubusercontent.com/38194372/114474322-42ce2b80-9bf6-11eb-9416-2928c73618a3.png)
and this is firefox:
![image](https://user-images.githubusercontent.com/38194372/114474379-62fdea80-9bf6-11eb-81cb-0ee72fa65fed.png)

**Comment by Nwardezir** [comment]
Still not fixed as of today 👎 
Using Chrome Version 93.0.4577.63 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/1235104/132069813-0e19446f-3c2a-4688-87be-f6abd80e2fef.png)

**Comment by nandvar** [comment]
Still not fixed
Version 97.0.4692.8 (Official Build) dev (x86_64
<img width="257" alt="Screenshot 2021-11-14 at 12 41 12 AM" src="https://user-images.githubusercontent.com/6960988/141662144-71b680e1-ae36-4eea-9acd-6ce4d31e34d5.png">
)

**Comment by sedlund** [comment]
Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/8109138/149074763-3e7fbc5a-3639-4dd9-a73a-54d8489f8c2f.png)

**Comment by joelshepherd** [comment]
Fix will land again in the next few days in `2.2.2`.
